export const PM_DASHBOARD_PANEL = 'PM_DASHBOARD_PANEL';
export const DEV_DASHBOARD_PANEL = 'DEV_DASHBOARD_PANEL';

export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const ACTIVE_PROJECTS_REQUEST = 'ACTIVE_PROJECTS_REQUEST';
export const ACTIVE_PROJECTS_SUCCESS = 'ACTIVE_PROJECTS_SUCCESS';
export const ACTIVE_PROJECTS_FAIL = 'ACTIVE_PROJECTS_FAIL';
export const ACTIVE_TASKS_REQUEST = 'ACTIVE_TASKS_REQUEST';
export const ACTIVE_TASKS_SUCCESS = 'ACTIVE_TASKS_SUCCESS';
export const ACTIVE_TASKS_FAIL = 'ACTIVE_TASKS_FAIL';

export const PROJECT_TASKS_REQUEST = 'PROJECT_REQUEST';
export const PROJECT_TASKS_SUCCESS = 'PROJECT_SUCCESS';
export const PROJECT_TASKS_FAIL = 'PROJECT_FAIL';
export const DEV_TASK_REQUEST = 'PROJECT_TASK_REQUEST';
export const DEV_TASK_SUCCESS = 'PROJECT_TASK_SUCCESS';
export const DEV_TASK_FAIL = 'PROJECT_TASK_FAIL';
